runtime: python39

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.55
  min_instances: 0
  max_instances: 5
  min_pending_latency: 2000ms
  max_pending_latency: automatic
  max_concurrent_requests: 200

includes:
  - env_variables.yaml
